pm_api_url           = "https://proxmox.example.com:8006/api2/json"
pm_api_token_id      = "terraform@pve!token"
pm_api_token_secret  = "your_token_secret"
pm_node              = "proxmox-node"
storage              = "local-lvm"
pfsense_iso          = "local:iso/pfSense-CE-2.6.0-RELEASE-amd64.iso"
kali_template        = "kali-template"
ubuntu_template      = "ubuntu-template"
